// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtamdkvdoncawhuwpnwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0YW1ka3Zkb25jYXdodXdwbndmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwODUzNTEsImV4cCI6MjA1ODY2MTM1MX0.FBG8u7z9EAkSLQeDAwpIJUhQ5n919eahumwfr4zNWeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);